version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_booking
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###


volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
